### ISSUE TITLE
SeparatedButtons: Use context.theme.textTheme.button instead of context.theme.textTheme.headline5 for the separating dots

### ISSUE THREAD

**Issue by MarcelGarus** [JonasWanke/black_hole_flutter#3]
Otherwise, the dot style doesn't necessarily match the button style:

![image](https://user-images.githubusercontent.com/8601189/136993094-7b1cbf42-9f13-4c77-a7bc-e0ca64bbe6a5.png)

**Comment by JonasWanke** [comment]
Because changing the default value would be a breaking change which seems overkill for this small modification, I added `separatedButtons.textStyle` to override this value as part of [v0.3.3](https://pub.dev/packages/black_hole_flutter/changelog#033--2021-10-14). The default value will be changed in the next breaking change release.

**Comment by JonasWanke** [comment]
Closing this since `SeparatedButtons` got removed in version 1.0.0: https://pub.dev/packages/black_hole_flutter/changelog#100--2023-01-24
